FROM 192.168.251.222:5000/mysql

MAINTAINER "le lab - Alain Dhennin <alain.dhennin@atos.net>"


# copie du fichier d'initialisation des tables et donnees
COPY tuto.sql /docker-entrypoint-initdb.d/

 


